# Generated by Django 3.0.8 on 2020-10-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOfTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_api', models.TextField()),
                ('date', models.DateField()),
                ('city_from', models.TextField()),
                ('city_to', models.TextField()),
                ('price', models.FloatField()),
                ('booking_token', models.TextField()),
                ('flights_checked', models.NullBooleanField()),
                ('flights_invalid', models.NullBooleanField()),
                ('price_change', models.NullBooleanField()),
            ],
        ),
    ]
